const menuList = [
  {
    menuId: "1",
    menuName: "系统管理",
    parentId: "0",
    orderNum: "1",
    path: "system",
    component: "",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "M",
    visible: 0,
    status: 0,
    perms: "",
    icon: "el-icon-location",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
  {
    menuId: "2",
    menuName: "系统监控",
    parentId: "0",
    orderNum: "2",
    path: "monitor",
    component: "",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "M",
    visible: 0,
    status: 0,
    perms: "",
    icon: "el-icon-location",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
  {
    menuId: "100",
    menuName: "用户管理",
    parentId: "1",
    orderNum: "1",
    path: "user",
    component: "system/user/index",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "C",
    visible: 0,
    status: 0,
    perms: "system:role",
    icon: "el-icon-location",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
  {
    menuId: "200",
    menuName: "角色管理",
    parentId: "2",
    orderNum: "1",
    path: "role",
    component: "system/role/index",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "C",
    visible: 0,
    status: 0,
    perms: "system:role",
    icon: "el-icon-location",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
];
export default menuList;
