const vegetableList = [
  {
    id: 1,
    title: "螺丝椒",
    img: require("@/assets/images/order/luosijiao.png"),
    price: 8,
    unit: "kg",
    amount: 0,
  },
  //   {
  //     id: 2,
  //     title: "螺丝椒",
  //     img: require("@/assets/images/order/luosijiao.png"),
  //     price: 8,
  //     unit: "kg",
  //     amount: 0,
  //   },
  //   {
  //     id: 3,
  //     title: "螺丝椒",
  //     img: require("@/assets/images/order/luosijiao.png"),
  //     price: 8,
  //     unit: "kg",
  //     amount: 0,
  //   },
  //   {
  //     id: 4,
  //     title: "螺丝椒",
  //     img: require("@/assets/images/order/luosijiao.png"),
  //     price: 8,
  //     unit: "kg",
  //     amount: 0,
  //   },
  //   {
  //     id: 5,
  //     title: "螺丝椒",
  //     img: require("@/assets/images/order/luosijiao.png"),
  //     price: 8,
  //     unit: "kg",
  //     amount: 0,
  //   },
  //   {
  //     id: 6,
  //     title: "螺丝椒",
  //     img: require("@/assets/images/order/luosijiao.png"),
  //     price: 8,
  //     unit: "kg",
  //     amount: 0,
  //   },
  //   {
  //     id: 7,
  //     title: "螺丝椒",
  //     img: require("@/assets/images/order/luosijiao.png"),
  //     price: 8,
  //     unit: "kg",
  //     amount: 0,
  //   },
  //   {
  //     id: 8,
  //     title: "螺丝椒",
  //     img: require("@/assets/images/order/luosijiao.png"),
  //     price: 8,
  //     unit: "kg",
  //     amount: 0,
  //   },

  //   {
  //     id: 9,
  //     title: "螺丝椒",
  //     img: require("@/assets/images/order/luosijiao.png"),
  //     price: 8,
  //     unit: "kg",
  //     amount: 0,
  //   },
  //   {
  //     id: 10,
  //     title: "螺丝椒",
  //     img: require("@/assets/images/order/luosijiao.png"),
  //     price: 8,
  //     unit: "kg",
  //     amount: 0,
  //   },
];
export default vegetableList;
